name: al_khalil
description: Moseqeu system with clean archeticture.

publish_to: 'none' 

version: 5.3.4

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  http: ^0.13.5
  provider: ^6.0.5
  circular_countdown_timer: ^0.2.3
  flutter_localizations:
    sdk: flutter
  # intl: ^0.18.0
  localization: ^2.1.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.2.0
  image_picker: ^0.8.7+3
  permission_handler: ^10.2.0
  image_cropper: ^3.0.3
  dismissible_page: ^1.0.2
  url_launcher: ^6.1.11
  loading_animation_widget: ^1.2.0+4
  google_fonts: ^4.0.1
  awesome_dialog: ^3.1.0
  flutter_typeahead: ^4.6.0
  package_info_plus: ^3.0.3
  flutter_cupertino_date_picker_fork: ^1.0.7
  internet_connection_checker_plus: ^1.0.1
  go_router: ^9.0.3
  fluttertoast: ^8.2.1
  flutter_native_splash: ^2.2.19
  shimmer: ^3.0.0
  awesome_notifications: ^0.7.4+1
  connectivity_plus: ^4.0.1
  url_strategy: ^0.2.0

dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/languages/en.json
    - assets/languages/ar.json
    - assets/images/
    - assets/audios/
    - assets/animations/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700